version: '3.8'

services:
  order-processing-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID}
      - AWS_QUEUE_NAME=${AWS_QUEUE_NAME}
      - AWS_QUEUE_URL=${AWS_QUEUE_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STATE_MACHINE_NAME=${AWS_STATE_MACHINE_NAME}
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - order-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  order-network:
    driver: bridge 